package circuits

const (
	ErrorEmptyAuthClaimProof             = "empty auth claim mtp proof"
	ErrorEmptyAuthClaimInNewStateProof   = "empty auth claim in new state mtp proof"
	ErrorEmptyAuthClaimNonRevProof       = "empty auth claim non-revocation mtp proof"
	ErrorEmptyChallengeSignature         = "empty challenge signature"
	ErrorEmptyClaimSignature             = "empty claim signature"
	ErrorEmptyClaimProof                 = "empty claim mtp proof"
	ErrorEmptyClaimNonRevProof           = "empty claim non-revocation mtp proof"
	ErrorEmptyIssuerAuthClaimProof       = "empty issuer auth claim mtp proof"
	ErrorEmptyIssuerClaim                = "empty issuer claim"
	ErrorEmptyStateCommitmentClaim       = "empty state commitment claim"
	ErrorEmptyIssuerAuthClaimNonRevProof = "empty issuer auth claim non-revocation mtp proof"
	ErrorEmptyJsonLDQueryProof           = "empty JSON-LD query mtp proof"
	ErrorEmptyJsonLDQueryValue           = "empty JSON-LD query value"
	ErrorEmptyJsonLDQueryPath            = "empty JSON-LD query path"
	ErrorEmptyQueryValue                 = "empty query value"
	ErrorEmptyJsonLDQueryValues          = "empty JSON-LD query values"
	ErrorEmptyID                         = "empty ID"
	ErrorEmptyChallenge                  = "empty challenge"
	ErrorEmptyGISTProof                  = "empty GIST identity mtp proof"
	ErrorEmptyRequestID                  = "empty request ID"
	ErrorInvalidProofType                = "invalid proof type"
	ErrorEmptySignatureProof             = "empty signature proof"
	ErrorEmptyMTPProof                   = "empty MTP proof"
	ErrorInvalidValuesArrSize            = "invalid query Values array size"
)
